version: "3.8"

services:
  app:
    build: .
    container_name: transfermarkt_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
